name: newproject
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  convex_bottom_bar: ^2.6.0
  fluttertoast: ^7.1.6
  email_validator: ^1.0.6
  http: ^0.12.2 
  flutter_spinkit: ^4.1.2+1
  google_sign_in: ^4.5.9
  shared_preferences: ^0.5.12+4
  google_maps_flutter: ^1.2.0
  location: ^3.2.4
  geolocator: ^6.2.0
  geocoder: ^0.2.1
  flutter_launcher_icons: ^0.8.1
  flutter_launcher_name: ^0.0.1
  image_picker: ^0.6.7+22
  intl: ^0.16.1
  syncfusion_flutter_calendar: ^18.4.43
  dotted_line: ^2.0.2
  cloud_firestore: ^0.13.4+2 #^0.16.0
  charts_flutter: ^0.9.0
  progress_dialog: 
  flutter_calendar_carousel: ^1.5.1
  text_tools: ^0.0.2
  permission_handler: ^5.0.1+1
  dio: ^3.0.10
  flutter_audio_recorder: ^0.5.5
  path_provider: ^1.1.0
  file: ^5.0.4
  audio_recorder: ^1.0.2
  path: ^1.7.0
  permissions_plugin: ^1.1.4
  tflite_flutter: ^0.5.0
  camera: ^0.5.8+5
  firebase_ml_vision: ^0.9.6+2
  image: ^2.1.19
  #Iamge Slider
  carousel_slider: ^3.0.0
  carousel_pro: ^1.0.0
  #audio
  audioplayers: ^0.16.2
  #Photo View with Zoom
  photo_view: ^0.9.2
  flutter_datetime_picker: ^1.5.0
  date_time_picker: ^1.1.1
#  flutter_cupertino_date_picker:
  #Share-Intent
  url_launcher: ^5.4.10
  share: ^0.6.4+3
#  jitsi_meet: ^2.0.0
#  flutter_visualizers:
#  flutter_launch:
  file_picker: ^2.1.6
  advance_pdf_viewer: ^1.2.2 #^1.1.3
  clipboard: ^0.1.2+8
  flutter_gifimage: ^1.0.1
  firebase_messaging: ^6.0.13 #^8.0.0-dev.12
  flutter_ringtone_player: ^2.0.0
  overlay_support: ^1.0.5
  flutter_inappwebview: ^4.0.0+4
  syncfusion_flutter_charts: ^18.4.43


dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  image_path: "Images/app-logo.png"
  android: true
  ios: true
flutter_launcher_name:
  name: "MyOffice"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - Images/license.png
    - Images/splash.png
    - Images/login/loginBg.png
    - Images/login/lock.png
    - Images/login/blind.png
    - Images/login/mail.png
    - Images/forgotPassword/forgot.png
    - Images/home/menu.png
    - Images/home/search.png
    - Images/home/my_ofc_logo.PNG
    - Images/home/doc.png
    - Images/drawer/cross.png
    - Images/drawer/chart.png
    - Images/drawer/chat.png
    - Images/drawer/doc.png
    - Images/drawer/event.png
    - Images/drawer/leads.png
    - Images/drawer/logme.png
    - Images/drawer/logout.png
    - Images/drawer/my-tasks.png
    - Images/drawer/phone.png
    - Images/drawer/query.png
    - Images/home/homelogo.png
    - Images/home/homechart.png
    - Images/home/homeCalendar.png
    - Images/home/homechat.png
    - Images/home/homequery.png
    - Images/home/homeleads.png
    - Images/home/hometask.png
    - Images/home/homelogme.png
    - Images/home/Group 1.png
    - Images/home/homedoc.png
    - Images/home/Calendar (2).png
    - Images/home/chart (2).png
    - Images/home/doc (1).png
    - Images/home/chat (2).png
    - Images/home/leads (2).png
    - Images/home/logme 2.png
    - Images/home/query (2).png
    - Images/home/task (2).png
    - Images/whatsappPro.png
    - Images/app-logo.png
    - Images/attach 1.png
    - Images/Group 15.png
    - Images/Send (1).png
    - Images/task/description-gray.png
    - Images/task/volume.png
    - Images/task/image-gray.png
    - Images/task/task title.png
    - Images/task/audio.png
    - Images/newHomeIcons/attendance.png
    - Images/newHomeIcons/calendar.png
    - Images/newHomeIcons/daily.png
    - Images/newHomeIcons/chat.png
    - Images/MYOffice-Icon.png
    - Images/task/add notes.png
    - Images/task/Add task banner.png
    - Images/newHomeIcons/projectname-gray.png
    - Images/newHomeIcons/worklog.png
    - Images/newHomeIcons/worklog-white.png
    - Images/task/add worklog banner.png
    - Images/misc/calendar 1.png
    - Images/misc/user 1.png
    - Images/misc/user 1 (1).png
    - Images/misc/user 1 (2).png
    - Images/misc/user 1 (3).png
    - Images/LeaderBoard/Rectangle 2.png
    - Images/LeaderBoard/user 2 (1).png
    - Images/payslipLogo.png
    - Images/task/calendar 1 (1).png
    - Images/misc/whatsapp.png
    - Images/misc/unkn.png
    - Images/misc/chat.png
    - Images/misc/a_platform.png
    - Images/misc/gift.png
    - Images/misc/offer.png
    - Images/misc/inventory.png
    - Images/misc/m_inv_count.png
    - Images/misc/inventoryList.png
    - Images/no-image-icon-1.jpg
    - Images/Profile/mail 1.png
    - Images/Profile/phone 1.png
    - Images/Profile/user 1 (4).png
    - Images/Profile/Vector.png
    - Images/Profile/Vector (1).png
    - Images/Profile/Vector (2).png
    - Images/Profile/Vector (3).png
    - Images/misc/addexpnse.png
    - Images/newHomeIcons/Rectangle 1233.png
    - Images/newIcons/leaderboard.png
    - Images/newIcons/video conference.png
    - Images/newIcons/kpi.png
    - Images/newIcons/analytics.png
    - Images/newIcons/Path.png
    - Images/ezgif.com-crop.gif
    - Images/misc/calendar 1 (3).png
    - Images/newIcons/claim 1.png
    - Images/newIcons/leave.png
    - Images/newIcons/file (1).png
    - Images/newIcons/contact-book 1.png
    - Images/misc/work-from-home (4).png
    - Images/misc/work tag (2).png
    - Images/misc/wallet 1.png
    - Images/misc/wallet (4).png
    - Images/misc/tickt (1).png
    - Images/misc/reminder (7).png
    - Images/misc/reminder (4).png
    - Images/misc/project (4).png
    - Images/misc/knowledge 1 (1).png
    - Images/misc/knowledge (4).png
    - Images/misc/offers.png
    - Images/misc/Inventory (1).png
    - Images/misc/expense.png
    - Images/login/inventory.png
    - Images/login/expense-white.png
    - Images/newHomeIcons/more.png
    - Images/login/logo21.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Medium.ttf
        - asset: fonts/Montserrat-SemiBold.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
